# This workflow update the sample.html file as that's what we use to prepare
# newsletters.

name: Update from RSS feeds

on:
  schedule:
    # Run every day at 3:04 AM.
    - cron: '4 3 * * *'

  workflow_dispatch:

jobs:
  update:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build --if-present
    - run: node index.js > docs/sample.html
    - uses: stefanzweifel/git-auto-commit-action@v4
